/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FollowRequest {
  'id' : FollowRequestId,
  'status' : { 'pending' : null } |
    { 'denied' : null } |
    { 'approved' : null },
  'followedId' : UserId,
  'followerId' : UserId,
}
export type FollowRequestId = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'approveFollowRequest' : ActorMethod<[FollowRequestId], boolean>,
  'createFollowRequest' : ActorMethod<[UserId, UserId], FollowRequestId>,
  'denyFollowRequest' : ActorMethod<[FollowRequestId], boolean>,
  'getAllPendingFollowRequests' : ActorMethod<[], Array<FollowRequest>>,
  'getFollowRequest' : ActorMethod<[FollowRequestId], [] | [FollowRequest]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];