/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FollowRequestId = IDL.Nat;
export const UserId = IDL.Principal;
export const FollowRequest = IDL.Record({
  'id' : FollowRequestId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  }),
  'followedId' : UserId,
  'followerId' : UserId,
});

export const idlService = IDL.Service({
  'approveFollowRequest' : IDL.Func([FollowRequestId], [IDL.Bool], []),
  'createFollowRequest' : IDL.Func([UserId, UserId], [FollowRequestId], []),
  'denyFollowRequest' : IDL.Func([FollowRequestId], [IDL.Bool], []),
  'getAllPendingFollowRequests' : IDL.Func(
      [],
      [IDL.Vec(FollowRequest)],
      ['query'],
    ),
  'getFollowRequest' : IDL.Func(
      [FollowRequestId],
      [IDL.Opt(FollowRequest)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FollowRequestId = IDL.Nat;
  const UserId = IDL.Principal;
  const FollowRequest = IDL.Record({
    'id' : FollowRequestId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'denied' : IDL.Null,
      'approved' : IDL.Null,
    }),
    'followedId' : UserId,
    'followerId' : UserId,
  });
  
  return IDL.Service({
    'approveFollowRequest' : IDL.Func([FollowRequestId], [IDL.Bool], []),
    'createFollowRequest' : IDL.Func([UserId, UserId], [FollowRequestId], []),
    'denyFollowRequest' : IDL.Func([FollowRequestId], [IDL.Bool], []),
    'getAllPendingFollowRequests' : IDL.Func(
        [],
        [IDL.Vec(FollowRequest)],
        ['query'],
      ),
    'getFollowRequest' : IDL.Func(
        [FollowRequestId],
        [IDL.Opt(FollowRequest)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };