/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface FollowRequest {
    id: FollowRequestId;
    status: Variant_pending_denied_approved;
    followedId: UserId;
    followerId: UserId;
}
export type FollowRequestId = bigint;
export enum Variant_pending_denied_approved {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export interface backendInterface {
    approveFollowRequest(requestId: FollowRequestId): Promise<boolean>;
    createFollowRequest(followerId: UserId, followedId: UserId): Promise<FollowRequestId>;
    denyFollowRequest(requestId: FollowRequestId): Promise<boolean>;
    getAllPendingFollowRequests(): Promise<Array<FollowRequest>>;
    getFollowRequest(requestId: FollowRequestId): Promise<FollowRequest | null>;
}
import type { FollowRequest as _FollowRequest, FollowRequestId as _FollowRequestId, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveFollowRequest(arg0: FollowRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveFollowRequest(arg0);
            return result;
        }
    }
    async createFollowRequest(arg0: UserId, arg1: UserId): Promise<FollowRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowRequest(arg0, arg1);
            return result;
        }
    }
    async denyFollowRequest(arg0: FollowRequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.denyFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyFollowRequest(arg0);
            return result;
        }
    }
    async getAllPendingFollowRequests(): Promise<Array<FollowRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingFollowRequests();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingFollowRequests();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowRequest(arg0: FollowRequestId): Promise<FollowRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowRequest(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowRequest(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FollowRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowRequest): FollowRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FollowRequest]): FollowRequest | null {
    return value.length === 0 ? null : from_candid_FollowRequest_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FollowRequestId;
    status: {
        pending: null;
    } | {
        denied: null;
    } | {
        approved: null;
    };
    followedId: _UserId;
    followerId: _UserId;
}): {
    id: FollowRequestId;
    status: Variant_pending_denied_approved;
    followedId: UserId;
    followerId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_variant_n4(_uploadFile, _downloadFile, value.status),
        followedId: value.followedId,
        followerId: value.followerId
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): Variant_pending_denied_approved {
    return "pending" in value ? Variant_pending_denied_approved.pending : "denied" in value ? Variant_pending_denied_approved.denied : "approved" in value ? Variant_pending_denied_approved.approved : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowRequest>): Array<FollowRequest> {
    return value.map((x)=>from_candid_FollowRequest_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
